name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - master


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document NewtonEuler
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/NewtonEuler/





      - name: Save NewtonEuler artifact
        uses: actions/upload-artifact@v1
        with:
          name: NewtonEuler.pdf
          path: Slides/NewtonEuler/main.pdf





      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add Slides/NewtonEuler/main.pdf

          git commit -m "Update compiled PDFs"
          git push
