name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - master


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document Electrodynamics
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Electrodynamics/

      - name: Compile LaTeX document Filters
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Filters/

      - name: Compile LaTeX document NewtonEuler
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/NewtonEuler/

      - name: Compile LaTeX document DC_motor
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/DC_motor/

      - name: Compile LaTeX document DC_motor_properties
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/DC_motor_properties/

      - name: Compile LaTeX document Second_order_systems
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Second_order_systems/

      - name: Compile LaTeX document PID_control
        uses: xu-cheng/latex-action@master
        with:
          root_file: Slides/PID_control/

      - name: Compile LaTeX document Gearbox
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Gearbox/

      - name: Compile LaTeX document Sensors
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Sensors/

      - name: Compile LaTeX document LagFrequency
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/LagFrequency/

      - name: Compile LaTeX document Series_Elastic_Actuator
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Series_Elastic_Actuator/

      - name: Compile LaTeX document New_Actuators_Types
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/New_Actuators_Types/

      - name: Compile LaTeX document Motor_Types
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: Slides/Motor_Types/





      - name: Save Electrodynamics artifact
        uses: actions/upload-artifact@v1
        with:
          name: Electrodynamics.pdf
          path: Slides/Electrodynamics/main.pdf

      - name: Save Filters artifact
        uses: actions/upload-artifact@v1
        with:
          name: Filters.pdf
          path: Slides/Filters/main.pdf

      - name: Save NewtonEuler artifact
        uses: actions/upload-artifact@v1
        with:
          name: NewtonEuler.pdf
          path: Slides/NewtonEuler/main.pdf

      - name: Save DC_motor artifact
        uses: actions/upload-artifact@v1
        with:
          name: DC_motor.pdf
          path: Slides/DC_motor/main.pdf

      - name: Save DC_motor_properties artifact
        uses: actions/upload-artifact@v1
        with:
          name: DC_motor_properties.pdf
          path: Slides/DC_motor_properties/main.pdf

      - name: Save Second_order_systems artifact
        uses: actions/upload-artifact@v1
        with:
          name: Second_order_systems.pdf
          path: Slides/Second_order_systems/main.pdf

      - name: Save PID_control artifact
        uses: actions/upload-artifact@v1
        with:
          name: PID_control.pdf
          path: Slides/PID_control/main.pdf

      - name: Save Gearbox artifact
        uses: actions/upload-artifact@v1
        with:
          name: Gearbox.pdf
          path: Slides/Gearbox/main.pdf

      - name: Save Sensors artifact
        uses: actions/upload-artifact@v1
        with:
          name: Sensors.pdf
          path: Slides/Sensors/main.pdf

      - name: Save LagFrequency artifact
        uses: actions/upload-artifact@v1
        with:
          name: LagFrequency.pdf
          path: Slides/LagFrequency/main.pdf

      - name: Save Series_Elastic_Actuator artifact
        uses: actions/upload-artifact@v1
        with:
          name: Series_Elastic_Actuator.pdf
          path: Slides/Series_Elastic_Actuator/main.pdf

      - name: Save New_Actuators_Types artifact
        uses: actions/upload-artifact@v1
        with:
          name: New_Actuators_Types.pdf
          path: Slides/New_Actuators_Types/main.pdf

      - name: Save Motor_Types artifact
        uses: actions/upload-artifact@v1
        with:
          name: Motor_Types.pdf
          path: Slides/Motor_Types/main.pdf





      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add Slides/Electrodynamics/main.pdf
          git add Slides/Filters/main.pdf
          git add Slides/NewtonEuler/main.pdf
          git add Slides/DC_motor/main.pdf
          git add Slides/DC_motor_properties/main.pdf
          git add Slides/Second_order_systems/main.pdf
          git add Slides/PID_control/main.pdf
          git add Slides/Gearbox/main.pdf
          git add Slides/Sensors/main.pdf
          git add Slides/LagFrequency/main.pdf
          git add Slides/Series_Elastic_Actuator/main.pdf
          git add Slides/New_Actuators_Types/main.pdf
          git add Slides/Motor_Types/main.pdf

          git commit -m "Update compiled PDFs"
          git push



